@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXIiLCJlbWFpbCI6InVzZXJAbmFtZS5jb20iLCJpYXQiOjE2MzA0NDY0NTQsImV4cCI6MTYzMDQ1MDA1NH0.8o1NGfL63-PKRla9IlGupzfmkP2ULVgO_L0T-vtZaaQ
@testPOSTBody = { "name": "test POST", "method": "POST", "description": "sending payload" }
@testPUTBody = { "name": "test PUT", "method": "PUT", "description": "sending payload" }
@testDELETEBody = { "name": "test DELETE", "method": "DELETE", "description": "sending payload" }

### GET base
GET http://{{host}}/api

### GET api/tests
GET http://{{host}}/api/tests

### POST api/tests
# curl -X POST http://{{host}}/api/tests/123 -H 'Content-Type: {{contentType}}' -d '{{testPOSTBody}}'
POST http://{{host}}/api/tests/123
Content-Type: {{contentType}}'

{{testPOSTBody}}

### PUT api/tests
# curl -X PUT http://{{host}}/api/tests/123 -H 'Content-Type: {{contentType}}' -d '{{testPUTBody}}'
PUT http://{{host}}/api/tests/123
Content-Type: {{contentType}}'

{{testPUTBody}}

### DELETE api/tests
# curl -X DELETE  http://{{host}}/api/tests/123 -H 'Content-Type: {{contentType}}' -d '{{testDELETEBody}}'
DELETE  http://{{host}}/api/tests/123
Content-Type: {{contentType}}'

{{testDELETEBody}}