@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@testPOSTBody = { "name": "test POST", "method": "POST", "description": "sending payload" }
@testPUTBody = { "name": "test PUT", "method": "PUT", "description": "sending payload" }
@testDELETEBody = { "name": "test DELETE", "method": "DELETE", "description": "sending payload" }


### GET base
# curl -X GET http://{{host}}/api/v1 -H 'Content-Type:{{contentType}}'
GET http://{{host}}/api/v1 HTTP/1.1
Content-Type:{{contentType}}

### GET api/v1/tests
# curl -X GET http://{{host}}/api/v1/tests -H 'Content-Type:{{contentType}}'
GET http://{{host}}/api/v1/tests
Content-Type:{{contentType}}

### POST api/v1/tests
# curl -X POST http://{{host}}/api/v1/tests/123 -H 'Content-Type:{{contentType}}' -d '{{testPOSTBody}}'
POST http://{{host}}/api/v1/tests/123
Content-Type:{{contentType}}

{{testPOSTBody}}

### PUT api/v1/tests
# curl -X PUT http://{{host}}/api/v1/tests/123 -H 'Content-Type:{{contentType}}' -d '{{testPUTBody}}'
PUT http://{{host}}/api/v1/tests/123
Content-Type:{{contentType}}

{{testPUTBody}}

### DELETE api/v1/tests
# curl -X DELETE http://{{host}}/api/v1/tests/123 -H 'Content-Type:{{contentType}}' -d '{{testDELETEBody}}'
DELETE http://{{host}}/api/v1/tests/123
Content-Type:{{contentType}}

{{testDELETEBody}}
