### GET base
# curl -X GET http://localhost:8080/api/v1 -H 'Content-Type: application/json' -H 'Authorization: <token>'
GET http://localhost:8080/api/v1
Content-Type: application/json
Authorization: <token>

### GET api/v1/tests
# curl -X GET http://localhost:8080/api/v1/tests -H 'Content-Type: application/json' -H 'Authorization: <token>'
GET http://localhost:8080/api/v1/tests
Content-Type: application/json
Authorization: <token>

### POST api/v1/tests
# curl -X POST http://localhost:8080/api/v1/tests/123 -H 'Content-Type: application/json' -H 'Authorization: <token>' -d '{ "name": "test POST", "method": "POST", "description": "sending payload" }'
POST http://localhost:8080/api/v1/tests/123
Content-Type: application/json
Authorization: <token>
{ "name": "test POST", "method": "POST", "description": "sending payload" }

### PUT api/v1/tests
# curl -X PUT http://localhost:8080/api/v1/tests/123 -H 'Content-Type: application/json' -H 'Authorization: <token>' -d '{ "name": "test POST", "method": "POST", "description": "sending payload" }'
PUT http://localhost:8080/api/v1/tests/123
Content-Type: application/json
Authorization: <token>
{ "name": "test POST", "method": "POST", "description": "sending payload" }

### DELETE api/v1/tests
# curl -X DELETE http://localhost:8080/api/v1/tests/123 -H 'Content-Type: application/json' -H 'Authorization: <token>' -d '{ "name": "test POST", "method": "POST", "description": "sending payload" }'
DELETE http://localhost:8080/api/v1/tests/123
Content-Type: application/json
Authorization: <token>
{ "name": "test POST", "method": "POST", "description": "sending payload" }
