### GET base
http://localhost:8080/api/v1

### GET api/v1/tests
http://localhost:8080/api/v1/tests

### POST api/v1/tests
curl -X POST http://localhost:8080/api/v1/tests/123
-H 'Content-Type: application/json'
-d '{
    "name": "test POST",
    "method": "POST",
    "description": "sending payload"
}'

### PUT api/v1/tests
curl -X PUT http://localhost:8080/api/v1/tests/123
-H 'Content-Type: application/json'
-d '{
    "name": "test",
    "method": "PUT",
    "description": "sending payload"
}'


### DELETE api/v1/tests
curl -X DELETE  http://localhost:8080/api/v1/tests/123
-H 'Content-Type: application/json'
-d '{
    "name": "test",
    "method": "DELETE",
    "description": "sending payload"
}'
